# Optimized Cloud Build configuration
# Uses multi-stage builds and caching for faster builds

steps:
  # Step 0: Debug - List files and check Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['version']
    id: 'docker-version'
  
  # Step 1: Build the shared base image with dependencies
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target=build'
      - '--tag=event-driven-playground-base:latest'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/event-driven-playground-base:latest'
      - '--file=Dockerfile.base'
      - '.'
    id: 'build-base'
    waitFor: ['docker-version']

  # Step 2: Build the runtime base image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target=runtime'
      - '--tag=event-driven-playground-runtime:latest'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/event-driven-playground-runtime:latest'
      - '--file=Dockerfile.base'
      - '.'
    id: 'build-runtime'
    waitFor: ['build-base']

  # Step 3: Build services in parallel using the base image
  # Command Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/command-service:$SHORT_SHA'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/command-service:latest'
      - '--build-arg=SERVICE_NAME=command_service'
      - '--file=apps/command_service/Dockerfile.optimized'
      - '.'
    id: 'build-command-service'
    waitFor: ['build-runtime']

  # Query Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/query-service:$SHORT_SHA'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/query-service:latest'
      - '--build-arg=SERVICE_NAME=query_service'
      - '--file=apps/query_service/Dockerfile.optimized'
      - '.'
    id: 'build-query-service'
    waitFor: ['build-runtime']

  # Client Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/client-service:$SHORT_SHA'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/client-service:latest'
      - '--build-arg=SERVICE_NAME=client_service'
      - '--file=apps/client_service/Dockerfile.optimized'
      - '.'
    id: 'build-client-service'
    waitFor: ['build-runtime']

# Images to push to the registry
images:
  # Base images
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/event-driven-playground-base:latest'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/event-driven-playground-runtime:latest'
  # Service images with SHA tags
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/command-service:$SHORT_SHA'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/command-service:latest'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/query-service:$SHORT_SHA'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/query-service:latest'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/client-service:$SHORT_SHA'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/client-service:latest'

options:
  logging: GCS_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

# Shorter timeout since builds should be faster with caching
timeout: 900s

# Substitutions for versioning
substitutions:
  _REGION: 'asia-northeast1'
