# Optimized Cloud Build configuration
# Uses multi-stage builds and caching for faster builds

steps:
  # Step 0: Debug - List files and check Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['version']
    id: 'docker-version'
  
  # Step 1: Build all services with the main Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target=builder'
      - '--tag=event-driven-playground-builder:latest'
      - '--file=Dockerfile'
      - '.'
    id: 'build-all'
    waitFor: ['docker-version']

  # Step 2: Extract and push Client Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target=client_service'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/client-service:$SHORT_SHA'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/client-service:latest'
      - '--file=Dockerfile'
      - '.'
    id: 'build-client-service'
    waitFor: ['build-all']

  # Step 3: Extract and push Command Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target=command_service'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/command-service:$SHORT_SHA'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/command-service:latest'
      - '--file=Dockerfile'
      - '.'
    id: 'build-command-service'
    waitFor: ['build-all']

  # Step 4: Extract and push Query Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target=query_service'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/query-service:$SHORT_SHA'
      - '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/query-service:latest'
      - '--file=Dockerfile'
      - '.'
    id: 'build-query-service'
    waitFor: ['build-all']


# Images to push to the registry
images:
  # Service images with SHA tags
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/command-service:$SHORT_SHA'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/command-service:latest'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/query-service:$SHORT_SHA'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/query-service:latest'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/client-service:$SHORT_SHA'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/client-service:latest'

options:
  logging: GCS_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

# Shorter timeout since builds should be faster with caching
timeout: 900s

# Substitutions for versioning
substitutions:
  _REGION: 'asia-northeast1'
