steps:
  # マイグレーション用 Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-migrate'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile.migrate'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/migrate:latest'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # イメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-migrate'
    waitFor: ['build-migrate']
    args: ['push', '--all-tags', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/event-driven-playground/migrate']

  # Cloud Run Job を作成または更新
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-job'
    waitFor: ['push-migrate']
    args:
      - 'gcloud'
      - 'run'
      - 'jobs'
      - 'replace'
      - '--source=/workspace/cloud-run-job.yaml'
      - '--region=asia-northeast1'
      - '--project=$PROJECT_ID'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8