# Firestore Emulator のみのシンプルな構成
services:
  # 単一の Firestore Emulator（開発用）
  firestore:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: >
      sh -c "
      apt-get update && apt-get install -y openjdk-17-jre-headless &&
      gcloud emulators firestore start --host-port=0.0.0.0:8080
      "
    ports:
      - "8090:8080"  # Firestore API（Phoenix と競合しないポート）
    environment:
      - FIRESTORE_PROJECT_ID=demo-project
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      timeout: 3s
      retries: 30