# Google Cloud Monitoring ダッシュボード設定
displayName: "Elixir CQRS Monitoring"
mosaicLayout:
  columns: 12
  tiles:
    # Request Rate
    - width: 6
      height: 4
      widget:
        title: "Request Rate"
        xyChart:
          dataSets:
            - timeSeriesQuery:
                timeSeriesFilter:
                  filter: metric.type="run.googleapis.com/request_count"
                  aggregation:
                    alignmentPeriod: "60s"
                    perSeriesAligner: ALIGN_RATE
              plotType: LINE
              minAlignmentPeriod: "60s"
          timeshiftDuration: "0s"
          yAxis:
            label: "requests/sec"
            scale: LINEAR
    
    # Request Latency
    - width: 6
      height: 4
      xPos: 6
      widget:
        title: "Request Latency (p95)"
        xyChart:
          dataSets:
            - timeSeriesQuery:
                timeSeriesFilter:
                  filter: metric.type="run.googleapis.com/request_latencies"
                  aggregation:
                    alignmentPeriod: "60s"
                    perSeriesAligner: ALIGN_PERCENTILE_95
              plotType: LINE
              minAlignmentPeriod: "60s"
          yAxis:
            label: "ms"
            scale: LINEAR
    
    # Error Rate
    - width: 4
      height: 4
      yPos: 4
      widget:
        title: "Error Rate"
        xyChart:
          dataSets:
            - timeSeriesQuery:
                timeSeriesFilter:
                  filter: metric.type="run.googleapis.com/request_count" AND resource.label.response_code_class!="2xx"
                  aggregation:
                    alignmentPeriod: "60s"
                    perSeriesAligner: ALIGN_RATE
              plotType: STACKED_AREA
          yAxis:
            label: "errors/sec"
            scale: LINEAR
    
    # CPU Utilization
    - width: 4
      height: 4
      xPos: 4
      yPos: 4
      widget:
        title: "CPU Utilization"
        xyChart:
          dataSets:
            - timeSeriesQuery:
                timeSeriesFilter:
                  filter: metric.type="run.googleapis.com/container/cpu/utilizations"
                  aggregation:
                    alignmentPeriod: "60s"
                    perSeriesAligner: ALIGN_MEAN
              plotType: LINE
          yAxis:
            label: "%"
            scale: LINEAR
    
    # Memory Utilization
    - width: 4
      height: 4
      xPos: 8
      yPos: 4
      widget:
        title: "Memory Utilization"
        xyChart:
          dataSets:
            - timeSeriesQuery:
                timeSeriesFilter:
                  filter: metric.type="run.googleapis.com/container/memory/utilizations"
                  aggregation:
                    alignmentPeriod: "60s"
                    perSeriesAligner: ALIGN_MEAN
              plotType: LINE
          yAxis:
            label: "%"
            scale: LINEAR
    
    # Active Instances
    - width: 6
      height: 4
      yPos: 8
      widget:
        title: "Active Instances"
        xyChart:
          dataSets:
            - timeSeriesQuery:
                timeSeriesFilter:
                  filter: metric.type="run.googleapis.com/container/instance_count"
                  aggregation:
                    alignmentPeriod: "60s"
                    perSeriesAligner: ALIGN_MAX
              plotType: LINE
          yAxis:
            label: "instances"
            scale: LINEAR
    
    # Database Connections
    - width: 6
      height: 4
      xPos: 6
      yPos: 8
      widget:
        title: "Database Connections"
        xyChart:
          dataSets:
            - timeSeriesQuery:
                timeSeriesFilter:
                  filter: metric.type="cloudsql.googleapis.com/database/postgresql/num_backends"
                  aggregation:
                    alignmentPeriod: "60s"
                    perSeriesAligner: ALIGN_MEAN
              plotType: LINE
          yAxis:
            label: "connections"
            scale: LINEAR

---
# アラートポリシー
apiVersion: monitoring.googleapis.com/v3
kind: AlertPolicy
metadata:
  name: high-error-rate
spec:
  displayName: "High Error Rate"
  conditions:
    - displayName: "Error rate > 1%"
      conditionThreshold:
        filter: |
          metric.type="run.googleapis.com/request_count" AND
          resource.type="cloud_run_revision" AND
          metric.label.response_code_class!="2xx"
        aggregations:
          - alignmentPeriod: "60s"
            perSeriesAligner: ALIGN_RATE
        comparison: COMPARISON_GT
        thresholdValue: 0.01
        duration: "300s"
  notificationChannels:
    - projects/PROJECT_ID/notificationChannels/CHANNEL_ID
  alertStrategy:
    autoClose: "1800s"

---
# SLO 定義
apiVersion: monitoring.googleapis.com/v3
kind: ServiceLevelObjective
metadata:
  name: availability-slo
spec:
  serviceLevelIndicator:
    requestBased:
      goodTotalRatio:
        goodServiceFilter: |
          metric.type="run.googleapis.com/request_count" AND
          resource.type="cloud_run_revision" AND
          metric.label.response_code_class="2xx"
        totalServiceFilter: |
          metric.type="run.googleapis.com/request_count" AND
          resource.type="cloud_run_revision"
  goal: 0.995
  rollingPeriod: "2592000s" # 30 days
  displayName: "99.5% Availability SLO"